### ISSUE TITLE
write in first area not work

### ISSUE THREAD

**Issue by taoloo897** [tomaskovacik/VAGFISWriter#14]
Hi. Nice job.
I tried to write some text in first area of a MFD screen from a passat 2008.
  fisWriter.initScreen(0,0,64,40,0x82);
  fisWriter.sendStringFS(1, 1 , 0x21, F("graphics"));
Nothing is display , the screen remaining in standar mode with standard dates on it.
If i change y1 from 40 from 78 to 88 it display my text. I want to display text only in first area and in the rest remaining the standard screen.
Can you help me with a suggestion? 
Thanks

**Comment by tomaskovacik** [comment]
why do not use radio mode? https://github.com/tomaskovacik/VAGFISWriter/blob/master/examples/text_in_radio_mode/text_in_radio_mode.ino

**Comment by taoloo897** [comment]
Thanks a lot, It works with HW intrerrupt and must coding the cluster for 2 lines.
The problem is with cluster sensor or other errors, on beanch if one of them appear what i want to display will disapper.
Thanks

**Comment by taoloo897** [comment]
DID exists posibility to show more than 8 characters on line?

**Comment by tomaskovacik** [comment]
in radio mode no, only in navigation mode and then I do not know if you can initialize only the upper part of the screen, I think no.

**Comment by taoloo897** [comment]
thanks for answers and for your time, i will change in navi mode.
